### ISSUE TITLE
Need typescript support!

### ISSUE THREAD

**Issue by skbr1234** [k-128/react-tradingview-embed#1]
This is excellent work! Much appreciated!

Can you please add typescript support as it's difficult to use the module in a typescript project...

`TypeScript error in /Users/zameer/Documents/front-end/src/App.tsx(14,46):
Could not find a declaration file for module 'react-tradingview-embed'. 
'/Users/zameer/Documents/front-end/node_modules/react-tradingview-embed/dist/index.js' implicitly has an 'any' type.
  Try npm install @types/react-tradingview-embed if it exists or add a new declaration (.d.ts) file containing declare module react-tradingview-embed;   TS7016`

**Comment by skbr1234** [comment]
Since, we do not have Typescript support as of now. To surpass this error and still be able to use the module - use [@ts-ignore](https://stackoverflow.com/a/51797086/2404470)

    // @ts-ignore
    import { TradingViewEmbed, widgetType } from "react-tradingview-embed";

**Comment by skbr1234** [comment]
@xnr-k I have fixed the typescript issue using your code as the base. Thanks for the good work! https://www.npmjs.com/package/react-typescript-tradingview-embed

**Comment by skbr1234** [comment]
I have fixed all the issues migrating to typescript. However, the .tsx and .ts distinction are not working! Can you please use the code to add typescript support to your module, please?

Have a look at the code at https://github.com/nordible/React-Typescript-Tradingview-Embed

**Comment by skbr1234** [comment]
I have managed to find a solution https://stackoverflow.com/a/58806662/2404470

**Comment by k-128** [comment]
added TypeScript support: https://github.com/k-128/react-tradingview-embed/commit/a986aa040b958d847fa631398175a710ce301f11
