### ISSUE TITLE
Next js issue

### ISSUE THREAD

**Issue by WonYong-Shin** [k-128/react-tradingview-embed#16]
when i add this library in next..js. 
It appears error.

`SyntaxError: Unexpected token 'export'`

**Comment by devgodeth** [comment]
same issue here

**Comment by tulindor** [comment]
It seems to be a typescript error on the import of some library from the component.

```
export { AdvancedChart } from "./components";
^^^^^^

SyntaxError: Unexpected token 'export'
```

This is what my console shows when i try to build the app.

**Comment by JoChaeWoo** [comment]
Check issue #6
