### ISSUE TITLE
Update chart when state used in it changes

### ISSUE THREAD

**Issue by Clish254** [k-128/react-tradingview-embed#5]
How can I reload the chart when state used in it changes? e.g the symbol in the Advanced chart changes. I thought the component will rerender when the state in it changes but it does not.

**Comment by memsjava** [comment]
this issues happen to me also, but i think better to test the props if there's a change in useEffect then load/reload, else no need to reRender.

**Comment by Malikx-Alee** [comment]
@Clish254  @memsjava  Have you found any solution to it?

**Comment by k-128** [comment]
Closing as it's a React related issue, else please repost with reproducible example, or simple https://codesandbox.io/s/react-new
