### ISSUE TITLE
How to set range as 5 years default

### ISSUE THREAD

**Issue by dougcodes** [k-128/react-tradingview-embed#8]
Hi, Quick question. Is it possible to set the range to 5 years when the chart first loads? I tried setting range="5Y", range="5y" and had no luck.
Thank you

**Comment by k-128** [comment]
It depends on TradingViews related widget, check its corresponding docs: <https://www.tradingview.com/widget/>

**Comment by k-128** [comment]
It depends on TradingViews related widget, check its corresponding docs: <https://www.tradingview.com/widget/>
